const gameConstants = {
    FETCH_GAMES_SUCCESS: "FETCH_GAMES_SUCCESS",
    FETCH_GAMES_FAIL: "FETCH_GAMES_FAIL",
    CREATE_GAME_ROOM_SUCCESS: "CREATE_GAME_ROOM_SUCCESS",
    CREATE_GAME_ROOM_FAIL: "CREATE_GAME_ROOM_FAIL",
    ENTER_ROOM_SUCCESS: "ENTER_ROOM_SUCCESS",
    FETCH_GAME_ROOMS_SUCCESS: "FETCH_GAME_ROOMS_SUCCESS",
    SET_LOADING: 'SET_LOADING'
};

export default gameConstants;