version: '3.7'

services:

  backend:
    restart: always
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    volumes:
      - './services/backend:/usr/src/app'
    environment:
      - FLASK_ENV=development
      - APP_ENV=development
      # - DATABASE_DEV_URL=mysql+pymysql://tryon:secret_password@database:3306/tryon_db
      # - DATABASE_PROD_URL=mysql+pymysql://tryon:secret_password@database:3306/tryon_db
      - DATABASE_DEV_URL=sqlite:///database.db
      - DATABASE_PROD_URL=sqlite:///database.db
      - SECRET_KEY=my_precious_secret_key
      - ADMIN_SECRET_KEY=admin_precious_secret_key
      - RECREATE_DB=true # true/false
    depends_on:
      - database
      - redis

  # database:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret_password
  #     MYSQL_USER: tryon
  #     MYSQL_PASSWORD: secret_password
  #     MYSQL_DATABASE: tryon_db
  #   volumes:
  #     - ./conf/mariadb-conf.d:/etc/mysql/mariadb.conf.d
  #     - ./conf/conf.d:/etc/mysql/conf.d/

  redis:
    restart: always
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/share/nginx/html'
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  redis-data: