const chatConstants = {
    FETCH_MESSAGES_SUCCESS: "FETCH_MESSAGES_SUCCESS",
    FETCH_MESSAGES_FAIL: "FETCH_MESSAGES_FAIL",
    CREATE_CHAT_ROOM_SUCCESS: "CREATE_CHAT_ROOM_SUCCESS",
    CREATE_CHAT_ROOM_FAIL: "CREATE_CHAT_ROOM_FAIL",
    ENTER_ROOM_SUCCESS: "ENTER_ROOM_SUCCESS"
};

export default chatConstants;