"""update database migration

Revision ID: 6e0baa95ea9a
Revises: 9821b784b0ad
Create Date: 2019-04-07 12:29:53.164247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e0baa95ea9a'
down_revision = '9821b784b0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('token', table_name='blacklist_tokens')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('blacklisted_on', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('token', 'blacklist_tokens', ['token'], unique=True)
    # ### end Alembic commands ###
