const gameConstants = {
    FETCH_GAMES_SUCCESS: "FETCH_GAMES_SUCCESS",
    FETCH_GAMES_FAIL: "FETCH_GAMES_FAIL",
    CREATE_GAME_ROOM_SUCCESS: "CREATE_GAME_ROOM_SUCCESS",
    CREATE_GAME_ROOM_FAIL: "CREATE_GAME_ROOM_FAIL"
};

export default gameConstants;