const friendConstants = {
    FETCH_FOLLOWINGS_SUCCESS: "FETCH_FOLLOWINGS_SUCCESS",
    FETCH_FOLLOWINGS_FAIL: "FETCH_FOLLOWINGS_FAIL",
    FETCH_FOLLOWERS_SUCCESS: "FETCH_FOLLOWERS_SUCCESS",
    FETCH_FOLLOWERS_FAIL: "FETCH_FOLLOWERS_FAIL",
    FOLLOW_FRIENDS_SUCCESS: "FOLLOW_FRIENDS_SUCCESS",
    FOLLOW_FRIENDS_FAIL: "FOLLOW_FRIENDS_FAIL"
};

export default friendConstants;